config_version = 2

[bar.default]
center = [ "workspaces", "recorder_2", "notes", "launcher", "todo" ]
end = [ "group:g3", "clipboard", "group:g4", "group:g5" ]
margin_edge = 0
margin_ends = 0
radius = 0
radius_bottom_left = 80
radius_bottom_right = 80
start = [ "shelly", "nix-monitor", "wallpaper", "clock", "group:g2", "sysmon", "weather" ]

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "launcher", "clock" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    border = ""
    fill = "surface_variant"
    foreground = "primary"
    id = "g2"
    members = [ "cpu", "ram", "temp" ]
    opacity = 1.0
    padding = 10.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g3"
    members = [ "audio_visualizer", "media" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g4"
    members = [ "tray" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    foreground = "tertiary"
    id = "g5"
    members = [ "notifications", "network", "bluetooth", "volume", "brightness", "battery", "session" ]
    opacity = 1.0
    padding = 10.0

[calendar]
enabled = true
refresh_minutes = 5

    [calendar.account.personal_google]
    name = "calendar"
    type = "google"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "dark_mode"

[[control_center.shortcuts]]
type = "media"

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000006", "desktop-widget-0000000000000008", "desktop-widget-0000000000000009" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = false

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 272.1436767578125
    box_width = 386.0
    cx = 960.0
    cy = 480.58203125
    enabled = false
    output = "eDP-1"
    rotation = 0.0
    type = "sticker"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        background = true
        background_opacity = 0.45000000000000001
        background_padding = 5.0
        background_radius = 0.0
        image_path = "/home/requisite/Pictures/misc/Frieren_new_funny_thumbnail.webp"
        opacity = 1.0

    [desktop_widgets.widget.desktop-widget-0000000000000008]
    box_height = 141.203125
    box_width = 378.3828125
    cx = 1590.1640625
    cy = 786.37109375
    enabled = false
    output = "eDP-1"
    rotation = 0.0
    type = "label"

        [desktop_widgets.widget.desktop-widget-0000000000000008.settings]
        background = false
        description = "Actiate Noctlaia"
        opacity = 1.0
        title = "Activate Noctalia"

    [desktop_widgets.widget.desktop-widget-0000000000000009]
    box_height = 0.0
    box_width = 0.0
    cx = 234.28515625
    cy = 415.30859375
    output = "eDP-1"
    rotation = 0.0
    type = "noctalia/timer:timer"

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = false

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 879.984375
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        show_login_button = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 186.8125
    box_width = 437.6923828125
    cx = 960.0
    cy = 211.75
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        clock_style = "digital"
        color = "secondary"
        format = " {:%-I:%M %p}"
        shadow = false

[nightlight]
enabled = true
temperature_day = 10000

[notification]
blacklist = [ "tauon", "hyprshot" ]

[plugin_settings."avivbintangaringga/nix-monitor"]
branch = "nixos-unstable"
clean_command = "nix-collect-garbage"
panel_open_near_click = false
panel_placement = "attached"
show_update_available_notification = false
update_command = "cd ~/nixos-dotfiles-2.0 && nix flake update && nh home switch ."

[plugin_settings."noctalia/notes"]
notes_dir = "~/Documents/talianotes"

[plugin_settings."noctalia/screen_recorder"]
audio_source = "both"
copy_to_clipboard = true
directory = "~/Videos"
video_source = "focused"

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/kaomoji", "noctalia/notes", "nightwatch75/todo" ]

[shell]
app_icon_color = "on_surface"
avatar_path = "/home/bean/Pictures/misc/b2e253dd2eb170b841469e4053bd15f1.jpg"
clipboard_confirm_clear_history = false
settings_show_advanced = true
show_location = false
time_format = "{:%-I:%M %p}"

    [shell.screenshot]
    save_to_file = false

[theme]
builtin = "Rosé Pine"
community_palette = "Lilac AMOLED"
custom_palette = "m3-content"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "foot", "gtk3", "gtk4", "ghostty", "hyprland", "kcolorscheme", "mango", "niri", "qt" ]
    community_ids = [
        "pywalfox",
        "zen-browser",
        "neovim",
        "vscode",
        "fuzzel",
        "discord",
        "opencode",
        "steam",
        "telegram",
        "yazi",
        "zathura",
        "hyprtoolkit"
    ]

[wallpaper]
directory = "/home/bean/Pictures/wallpapers/local"
edge_smoothness = 0.0
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/bean/Pictures/wallpapers/local/wallhaven-qrgqyq.jpg"

    [wallpaper.last]
    path = "/home/bean/Pictures/wallpapers/local/wallhaven-qrgqyq.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/bean/Pictures/wallpapers/local/wallhaven-qrgqyq.jpg"

    [[wallpaper.favorite]]
    community_palette = "Rosey AMOLED"
    palette_source = "community"
    path = "/home/bean/Pictures/wallpapers/local/isnt_she_lovely.png"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/bean/Pictures/wallpapers/local/wallhaven_xe73ro.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    community_palette = "Lilac AMOLED"
    palette_source = "community"
    path = "/home/bean/Pictures/wallpapers/local/wallhaven-mlgomm.png"
    theme_mode = "dark"

[weather]
address = "Toronto, Canada"

[widget.active_window]
capsule = true

[widget.battery]
display_mode = "graphic"

[widget.bluetooth]
show_label = true

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.clipboard]
capsule = true
capsule_fill = "on_secondary"
color = "primary"

[widget.clock]
capsule = true
capsule_fill = "surface_variant"
capsule_foreground = "secondary"
format = "{:%A, %B %e, %Y, %I:%M %p}"

[widget.nix-monitor]
colorize_glyph = false
show_text = false
type = "avivbintangaringga/nix-monitor:nix-monitor"

[widget.notes]
type = "noctalia/notes:notes"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.recorder_2]
type = "noctalia/screen_recorder:recorder"

[widget.shelly]
type = "joshuaslate/shelly:shelly"

[widget.spacer_2]
type = "spacer"

[widget.spacer_3]
type = "spacer"

[widget.sysmon]
capsule = true
stat = "gpu_vram"

[widget.taskbar]
anchor = true
group_by_workspace = true

[widget.todo]
type = "nightwatch75/todo:todo"

[widget.tray]
capsule = true

[widget.weather]
capsule = true

[widget.workspaces]
anchor = true
capsule_fill = "on_primary"